version: "3.8"
services:
    mongodb:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=max
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        networks:
            - goals
        image: mongo
    goals-backend:
        ports:
            - 80:80
        volumes:
            - logs:/logs
            - node_modules:/node_modules
        networks:
            - goals
        image: proxsee97/goals-backend
    goals-frontend:
        ports:
            - 3000:3000
        volumes:
            - .\frontend\src:/src
        networks:
            - goals
        image: proxsee97/goals-frontend
networks:
    goals:
volumes:
    data:
    logs:
    node_modules: